---
abstract: 'Moose-based role that adds serialization support to any class'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  JSON: 0
  Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Serializable
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::MOP: 0
  Moose::Role: 0
  Storable: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
